# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2022-01-07 21:30:44
"""
import arcpy
from sys import argv

def FuturePicker(Final="C:\\Users\\oliya\\OneDrive\\Desktop\\TGIS501\\lab_1\\MyProject\\MyProject.gdb\\AMLInventoryPoints2022_01_Se1", Clip_input="Bituminous_Coal_Mine_Permits_12022016", Data_input="AMLInventoryPoints2022_01"):  # FuturePicker

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False


    # Process: Clip (Clip) (analysis)
    arcpy.analysis.Clip(in_features=Data_input, clip_features=Clip_input, out_feature_class=Final, cluster_tolerance="")

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\oliya\OneDrive\Desktop\TGIS501\lab_1\MyProject\MyProject.gdb", workspace=r"C:\Users\oliya\OneDrive\Desktop\TGIS501\lab_1\MyProject\MyProject.gdb"):
        FuturePicker(*argv[1:])
